platform:
  self: platform
  version: &v '#'
  login:
    self: login
  dashboard:
    self: dashboard
  fiance:
    self: fiance
    transaction:
      self: transaction

angency:
  self: agency
  version: '#'
  login:
    self: login
  dashboard:
    self: dashboard





